data:
  train_path: "./dataset/train.csv"
  test_path: "./dataset/test.csv"
  result_path: "./dataset/result.csv"

test_size: 0.2

model_params:
  c: 4
  max_iter: 10000
  class_weight: "balanced"

vectorizer_params:
  max_features: 5000
  ngram_range: [1, 2]
  sublinear_tf: false
