data:
  train_path: "../dataset/train.csv"
  test_path: "../dataset/test.csv"
  result_path: "../dataset/result.csv"

model_params:
  C: 4
  max_iter: 10000
  class_weight: "balanced"

vectorizer_params:
  max_features: 50000
  sublinear_tf: true
