name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m nltk.downloader punkt stopwords averaged_perceptron_tagger wordnet
      - name: Lint with Ruff
        run: |
          ruff --ignore=F401,F405,F403,E501 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest tests/code --verbose --disable-warnings
#          pytest --dataset-loc=checkpoints/data.csv tests/data --verbose --disable-warnings
#          pytest tests/code --verbose --disable-warnings
#          pytest --model-loc=checkpoints/mnb_model.joblib --vectorizer-loc=checkpoints/vectorizer.pkl tests/model --verbose --disable-warnings
